version: "3.4"

services:
  py-api-srv:
    build: py-srv/api
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && python -m unittest && python app.py"
    ports:
      - 443
    environment:
      - WAIT_HOSTS=elasticsearch:9200
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - elasticsearch
      - kibana
      - redis
    links:
      - "elasticsearch:elasticsearch"
      - "redis:redis"

  py-web-srv:
    build: py-srv/web
    healthcheck:
      test: "exit 0"
    command: sh -c "/wait && python -m unittest && python app.py"
    ports:
      - 443:443
    environment:
      - WAIT_HOSTS=py-api-srv:443
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - py-api-srv
    links:
      - "py-api-srv:py-api-srv"

  redis:
    image: redis:latest

  elasticsearch:
    image: elasticsearch:7.12.0
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #  - ./es/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.12.0
    healthcheck:
      test: "exit 0"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "SERVER_NAME=127.0.0.1"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

#  py-api-test-srv:
#    build:
#      context: py-test-srv/api
#    command: sh -c "/wait && python app.py"
#    environment:
#      - WAIT_HOSTS=py-api-srv:443
#      - WAIT_HOSTS_TIMEOUT=300
#      - WAIT_SLEEP_INTERVAL=30
#      - WAIT_HOST_CONNECT_TIMEOUT=30
#    depends_on:
#      - py-api-srv
#    links:
#      - "py-api-srv:py-api-srv"

#  py-web-test-srv:
#    build:
#      context: py-test-srv/web
#    command: sh -c "/wait && python app.py"
#    environment:
#      - WAIT_HOSTS=py-web-srv:443, selenium:4444
#      - WAIT_HOSTS_TIMEOUT=300
#      - WAIT_SLEEP_INTERVAL=30
#      - WAIT_HOST_CONNECT_TIMEOUT=30
#    depends_on:
#      - py-web-srv
#      - selenium
#    links:
#      - "py-web-srv:py-web-srv"
#      - "selenium:selenium"
#
#  selenium:
#    image: selenium/standalone-firefox
#    hostname: selenium
#    ports:
#    - 4444:4444